### ISSUE TITLE
octokit issue

### ISSUE THREAD

**Issue by gaminglifex** [Tch1b0/JP-nuxt#35]
Hi! May I know have you encountered the following problem when using @octokit/restjs in nuxt3?
![image](https://user-images.githubusercontent.com/72642816/198447305-64ec499c-aab8-42f8-b437-e6c0beebe932.png)

**Comment by Tch1b0** [comment]
Hey @gaminglifex, I haven't heard of that problem yet. But I think that error also can't appear on my project, as all my github data fetching is done on the server while the error seems to only appear in the browser
